name: Docker Build and Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t dj .

    - name: Run Docker container
      run: docker run -d --name dj-container -p 8000:8000 dj
